[package]
name = "guessing_game"
version = "0.1.0"
authors = ["aloha1024 <aloha1024@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.3.14"